### ISSUE TITLE
Refactor code for python3

### ISSUE THREAD

**Issue by LuisBlanche** [CoherenceApi/docker-push-ssh#14]
Python 2 was abandoned , 
code uses some python 2 libararies like urllib2

**Comment by nmgeek** [comment]
```
$ docker-push-ssh
Traceback (most recent call last):
  File "/usr/local/bin/docker-push-ssh", line 3, in <module>
    from docker_push_ssh import cli
  File "/usr/local/lib/python3.6/dist-packages/docker_push_ssh/cli.py", line 19, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

**Comment by superhawk610** [comment]
For anybody else who ends up here, until Luis's PR (#15) is merged, you can install directly from Github

```plain
$ pip install --upgrade --user git+https://github.com/LuisBlanche/docker-push-ssh@python3
```
