### ISSUE TITLE
Installation instructions are lacking

### ISSUE THREAD

**Issue by Shardj** [CoherenceApi/docker-push-ssh#19]
I've not used pip before as I don't really develop with python, but I installed pip on my ubuntu instance with `sudo apt install python3-pip` and ran the requested `pip install docker-push-ssh` command. I then had to search and find that the bin path was ~/.local/bin which needed to be added to my $PATH. Then upon running `docker-push-ssh -h` I'm hit with 'ModuleNotFoundError: No module named 'urllib2'', and I don't seem to be able to install this missing module with pip install.

It would be great if any needed dependencies were installed with the `pip install docker-push-ssh` command.

**Comment by Shardj** [comment]
So it seems that this is a python2 program, so:

Install python 2

Install pip 2:
`curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py`
`sudo python2 get-pip.py`

Then as root use pip2 to install this repo
`sudo pip2 install docker-push-ssh`

**Comment by Shardj** [comment]
```
$ docker-push-ssh demo hello-world
Traceback (most recent call last):
  File "/usr/local/bin/docker-push-ssh", line 4, in <module>
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/docker_push_ssh/cli.py", line 208, in main
    assert args.ssh_identity_file is not None
AssertionError
```

Seems it's still not working for me anyway, hopefully someone knows where I'm going wrong here
